name: 'Lighthouse Viewer Action'
description: 'Greet someone and record the time'
inputs:
  resultsPath:
    description: 'Results path of Lighthouse-CI action.'
    required: true
    default: ''
  lighthouseOutcome:
    description: 'The outcome of Lighthouse-CI action. Set `continue-on-error` for Lighthouse-CI action and pass the outcome here to display Lighthouse report if assertion failed.'
    required: false
    default: 'success'
runs:
  using: 'node16'
  main: 'dist/index.js'
